title: <p align="center"> Deniz Sağmanlı </p>
logo: "/assets/img/headshot_circle.png?raw=true"
description:
  <p align="center">
  <a href="/assets/documents/resume.pdf" target="_blank" rel="noopener">Resume</a> |
  <a href="https://www.linkedin.com/in/deniz-sagmanli-a0787610b/" target="_blank" rel="noopener">LinkedIn</a> |
  <a href="https://github.com/dsagmanli" target="_blank" rel="noopener">GitHub</a>
  </p>
  
  <p align="center">
  Data Scientist - AI Developer
  </p>

theme: jekyll-theme-minimal
