title: <p align="center"> Deniz Sağmanlı </p>
logo: /assets/img/headshot_circle.png
description:
  <p align="center">
  <a href="/assets/documents/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/deniz-sagmanli-a0787610b/">LinkedIn</a> |
  <a href="https://github.com/dsagmanli">GitHub</a>
  </p>
  
  <p align="justify">
  Data Scientist - AI Developer
  </p>
show_downloads: false
theme: jekyll-theme-minimal
